# default configuration
baseURL = "http://localhost:1337"
languageCode = "en-gb"
summaryLength = "10"
theme = "kross-hugo"
title = "COPIM"

# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"


# js plugin
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"


# menu
[[menu.main]]
URL = "about-us"
name = "About"
weight = 1

[[menu.main]]
URL = "governance"
name = "Governance"
weight = 2

[[menu.main]]
URL = "work-package"
name = "Work packages"
weight = 3

[[menu.main]]
URL = "events"
name = "Workshops"
weight = 4


# default parameters
[params]
home = "Home"
logo = "images/copim-logo.png"
# theme colours
theme_color = "#FFFFFF"
hover_link = "#EB7F1D"
highlight_colour = "#EB7F1D"
# contact info
pubpub = "https://copim.pubpub.org/"
twitter = "https://twitter.com/COPIMproject"
zenodo = "https://zenodo.org/communities/copim/"
# meta description
author = "COPIM"
description = "Community-led Open Publication Infrastructures for Monographs"
# google analytics
google_analytics_id = "" # Your ID
# baidu site verification
baidu_site_verification = "" #Your verification code
# baidu analytics
baidu_analytics_id = "" #Your ID
# copyright
copyright = " [COPIM](/) and licensed under a [Creative Commons Attribution 4.0 International License (CC BY 4.0)](https://creativecommons.org/licenses/by/4.0/)."


# preloader
[params.preloader]
enable = false
preloader = "images/preloader.gif" # use png, jpg, svg or gif format

# contact
[params.contact]
enable = false
form_action = "#" # contact form works with : https://formspree.io

# google map
[params.map]
enable = false
gmap_api = ""
map_latitude = ""
map_longitude = ""
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 2

# social site
[[params.social]]
icon = "ti-book"
URL = "https://copim.pubpub.org/"

[[params.social]]
icon = "ti-twitter-alt"
URL = "https://twitter.com/COPIMproject"

[[params.social]]
icon = "ti-write"
URL = "https://zenodo.org/communities/copim/"

[[params.social]]
icon = "ti-github"
URL = "https://github.com/COPIM"
